### ISSUE TITLE
[bug]mirai内建bot存储库没有这个账号

### ISSUE THREAD

**Issue by Hamusuta0320** [kagg886/Seiko#23]
![Screenshot_20230730_215836_com.kagg886.seiko.debug.jpg](https://github.com/kagg886/Seiko/assets/55654842/66fac30a-2802-48f4-bc3a-f77034cd5a5d)

![Screenshot_20230730_215953_com.kagg886.seiko.debug.jpg](https://github.com/kagg886/Seiko/assets/55654842/a22d4fba-f016-41c4-b83b-9ac1d96cbd48)

**Comment by kagg886** [comment]
细想一下在这之前都干了些什么异常情况（
比如说频繁的开关bot什么的x

**Comment by Hamusuta0320** [comment]
> 细想一下在这之前都干了些什么异常情况（
> 比如说频繁的开关bot什么的x
> 这个bug几个月以前就出现了但是一直摸不清楚来源，也不知道如何复现

是的频繁开关

**Comment by Hamusuta0320** [comment]
这个我是进软件之后点击开关登录，然后就提示我bot主动下线，然后我一看开关还开着的，我就点击关闭，就出现那个警告了

**Comment by kagg886** [comment]
try with [c0a15d7](https://github.com/kagg886/Seiko/commit/c0a15d747c6c6d3807081b22af88c03c2f7bdac5)

**Comment by kagg886** [comment]
try with af6457c
